spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
logging:
  level:
    cd.cc: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: cd.cc.domain.po #别名扫描包，用户减小mapper xml的包名写法
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml 文件地址
  configuration:
    map-underscore-to-camel-case: true # 开启下划线和驼峰映射
    cache-enabled: false # 是否开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举工具类配置
  global-config:
    db-config:
      id-type: assign_id # 设置主键 id 为雪花算法生成
      update-strategy: not_null #更新策略：只更新非空字段




knife4j:
  enable: true
  openapi:
    title: 用户接口管理
    description: 描述
    version: 1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - cd.cc.controller

